### PR TITLE
Enhancement add medium pixelpoint widget

### PR DESCRIPTION
**Pull request by rysmaadit**
### Description

Add medium widget from [pixelpoint](https://medium-widget.pixelpoint.io/) to replace existing article content fetched from contentful

### Detail Task

`[add_trello_link]`

### Application Changes
- [x] Add `Blog.tsx` component to load pixelpoint widget
- [x] Update `articles.template.tsx` to change articles section to blog widget
- [x] Remove unused social site metadata from `gatsby-config.js`
- [x] Revert articles section on `articles.template.tsx`
- [x] Change aspect ratio width on `SiapaKami.tsx`

### Database Changes
- [x] None

### Configuration Changes
- [x] None

### Status
- [x] Ready for review

### Type of Changes
- [x] Enhancement

### Background for Purposing Changes (If any)

This changes are purposed to remove the human bottleneck from doing manual work updating content to contentful, remove redundancy rewriting content that has been posted in medium, also help increasing visitors to our medium channel

### Screenshot (If any)

### CODE REVIEW

**Comment by ramarahmanda** [comment]
Don't remove activity section. There will be 2 sections, activity/event and pujangga teknologi.
Change copywriting from `Ikuti Terus Blog Kita Di Kanal Medium` => `Ikuti berbagai perkembangan teknologi dari para pujangga teknologi kami`

**Comment by ramarahmanda** [comment]
Set same width container between `siapa kami section` and `blog section`

**Comment by rysmaadit** [comment]
> Don't remove activity section. There will be 2 sections, activity/event and pujangga teknologi.
> Change copywriting from `Ikuti Terus Blog Kita Di Kanal Medium` => `Ikuti berbagai perkembangan teknologi dari para pujangga teknologi kami`

Changed already applied, please comment into specific line/file

**Comment by rysmaadit** [comment]
> Set same width container between `siapa kami section` and `blog section`

Changed already applied, please comment into specific line/file

**Pull request merged**
